security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

name: liz

quoteServiceURL: http://quote-service-dev.cfapps.io/quote

